# The CF Space Developer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: space-developer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - patch
  - get
  - create

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - get
  - create
  - patch
  - delete
  - list

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - get
  - list
  - patch

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - get
  - list
  - create
  - patch

- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - get
  - list
  - create

- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - get
  - list
  - create
  - delete

- apiGroups:
    - services.cloudfoundry.org
  resources:
    - cfservicebindings
  verbs:
    - get
    - list
    - create
    - delete

- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - get
  - create
  - delete
  - list
  - patch

- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
